# Generated by Django 5.2.4 on 2025-07-28 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_timestampedmodel_delete_book_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='TimeStampedModel',
        ),
    ]
